version: 2.1
jobs:
  build-images:
    working_directory: ~/app
    docker:
      - image: cimg/base:2022.09
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker Images
          command: |
            export BUILD_NUM=$CIRCLE_BUILD_NUM
            docker-compose -f deployment/docker/docker-compose-build-prod.yaml build
      - run:
          name: Tag Images with Build Number
          command: |
            docker tag mzucc/tracker-frontend-prod mzucc/tracker-frontend-prod:ci-build-$CIRCLE_BUILD_NUM
            docker tag mzucc/tracker-backend mzucc/tracker-backend:ci-build-$CIRCLE_BUILD_NUM
      - run:
          name: Check Images
          command: docker image ls
      - run:
          name: Push Docker Images
          command: |
            echo BUILD_NUM $CIRCLE_BUILD_NUM
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/tracker-frontend-prod:ci-build-$CIRCLE_BUILD_NUM
            docker push $DOCKERHUB_USERNAME/tracker-backend:ci-build-$CIRCLE_BUILD_NUM
      - run:
          name: Deploy
          command: |
            export BUILD_NUM=$CIRCLE_BUILD_NUM
            ./deployment/k8s/deploy.sh
workflows:
  build:
    jobs:
      - build-images
    # - deploy:
    #     requires:
    #       - build-node
