version: 2.1
jobs:
  build-images:
    working_directory: ~/app
    docker:
      - image: cimg/base:2022.09
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker Images
          command: |
            docker-compose -f deployment/docker/docker-compose-build-prod.yaml build
workflows:
  build:
    jobs:
      - build-images
    # - deploy:
    #     requires:
    #       - build-node
