version: "3"
services:
  tracker-backend:
    build:
      context: ../../backend
    image: mzucc/tracker-backend
  tracker-frontend:
    build:
      context: ../../frontend
    image: mzucc/tracker-frontend


