version: "3.9"
services:
  tracker-backend:
    build:
      context: ../../backend
      args:
        BUILD_NUM: $BUILD_NUM 
    image: mzucc/tracker-backend
  tracker-frontend:
    build:
      context: ../../frontend
    image: mzucc/tracker-frontend


