apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frontend
  name: frontend
spec:
  selector:
    matchLabels:
      service: frontend
  replicas: 2
  template:
    metadata:
      labels:
        service: frontend
        api: external        
    spec:
      containers:
      - image: mzucc/tracker-frontend
        name: frontend
        imagePullPolicy: Always          
        ports:
        - containerPort: 5173
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m" 
        env:
          - name: VITE_AWS_REGION
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: AWS_REGION
          - name: VITE_AWS_COGNITO_USERPOOLID
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: AWS_COGNITO_USERPOOLID
          - name: VITE_AWS_COGNITO_CLIENTID
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: AWS_COGNITO_CLIENTID
          - name: VITE_API_URL
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: API_URL
      restartPolicy: Always

